oxr:
  app:
    name: currency-converter
    id: 1d3efa34b315486aa8a86c52a5d5f365
    base: EUR
  urls:
    base: http://localhost:9090/
    latest: /latest.json
    historical: /historical/%s.json
    currencies: /currencies.json
    convert: /convert
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/currency-converter

recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s
  site-key: 6LecDpIUAAAAAKAnYNWW2BpgcVW47wBSTip2xI-O
  secret-key: 6LecDpIUAAAAALFqkigPsoOJFZgqEY-uAHl0DNOF